#!/bin/sh

# Monitore
xrandr --output HDMI-1 --primary --mode 1920x1080 --rate 60

# Desktop-Workspaces
bspc monitor -d 1 2 3 4 5

# Fenster- und Desktopverhalten
bspc config border_width 2
bspc config window_gap 8
# bspc config window_gap 0
bspc config focused_border_color "#ff79c6"
bspc config normal_border_color "#44475a"
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true


# Startprogramme

#!/bin/sh

# Keybinding Daemon starten
pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-scale /home/random/wp.jpg &

polybar &

# picom &

# nwg-look -r &

# Catppuccin Mocha Mauve GTK-Theme setzen
gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Mocha-Mauve"

# Optional: Catppuccin Icons
gsettings set org.gnome.desktop.interface icon-theme "Catppuccin"
